### PR TITLE
Added Package.swift

### PR DESCRIPTION
**Pull request by simone-gasparini**
Issue #26 
- Current example, working.
- Import and use in our app via forked repo branch, working.

### CODE REVIEW

**Comment by TimOliver** [comment]
Oh wow! Thanks for doing that Simone!

Uh, is it necessary to have to move around the header and implementation files in the project though? 😅

**Comment by simone-gasparini** [comment]
Hi @TimOliver !!
I've spent 4 hour yesterday doing tests with SPM without success, I tried to specify the path in Package.swift, tried to bridge objc to swift, tried to add custom modulemap, and other test that i don't remember.
The only working situation with objc project is to move files in the directory structure that SPM expect.
If you have any other idea I can do a check. 😉

**Comment by TimOliver** [comment]
Hi @simone-gasparini!

Oh jeez. That's a long time to spend on this. Sorry for your trouble!

In any case, thanks for getting it started for me. I downloaded your fork, restored the header and implementation file to where they were, and then played with the SPM package.

I got this building: 

```swift
// swift-tools-version:5.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "TORoundedButton",
    platforms: [
        .iOS(.v10)
    ],
    products: [
        .library(
            name: "TORoundedButton",
            targets: ["TORoundedButton"]
        )
    ],
    targets: [
        .target(
            name: "TORoundedButton",
            path: "TORoundedButton",
            exclude: [
                "TORoundedButtonExample",
                "TORoundedButtonExampleTest",
                "TORoundedButtonExampleFramework"
            ]
        )
    ]
)
```

(The only thing that really needed changing was setting the `path:` property in `targets`)

That being said. I couldn't get it working with ``// swift-tools-version:4.0``, only 5.
Do you need 4.0 for a specific reason?

Thanks!

**Comment by simone-gasparini** [comment]
Hi @TimOliver !
No problem, I've worked on other packages this morning and found the `path` property that you have inserted here. I had in mind to do a check for this package in the afternoon, but you have preceded me.
For the swift version no problem.
I think that could be fine!

**Comment by simone-gasparini** [comment]
Hi @TimOliver 
I've tried your Package.swift with path, but does not work if the .h file is not in the Include subdirectory of TORoundedButton.

**Comment by TimOliver** [comment]
Hi @simone-gasparini! Thanks for trying! I'm sorry I don't have an easy way to test that over here.

I just did a bit of research and discovered this property of `Target`: 

```
    /// The path to the directory containing public headers of a C-family target.
    ///
    /// If this is `nil`, the directory will be set to `include`.
    public var publicHeadersPath: String?
```

I THINK this should hopefully do the trick:

```
// swift-tools-version:5.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "TORoundedButton",
    platforms: [
        .iOS(.v10)
    ],
    products: [
        .library(
            name: "TORoundedButton",
            targets: ["TORoundedButton"]
        )
    ],
    targets: [
        .target(
            name: "TORoundedButton",
            path: "TORoundedButton",
            exclude: [
                "TORoundedButtonExample",
                "TORoundedButtonExampleTest",
                "TORoundedButtonExampleFramework"
            ],
            publicHeadersPath: "TORoundedButton"
        )
    ]
)
```

Can you please try that? I'd really rather not change the locations of the files if we can help it, since I have a pretty standard project pattern I use, and it might mess with the CI.

**Comment by simone-gasparini** [comment]
No, no way... I've tried 2 different properties (see last 2 commits) but no one work.
The only working solution is to move .h files to Include.

**Comment by TimOliver** [comment]
Okay. If it can’t be helped, then I guess that’s that.

Thank you so much for trying. :)

**Comment by simone-gasparini** [comment]
@TimOliver no wait.. the right commit is this one: https://github.com/TimOliver/TORoundedButton/pull/27/commits/1202b6ae188a0f9c6543241a89912cc017ea9a5b
If you revert the pull request, i will clean all and do a new pull request with the minimum changes

**Comment by TimOliver** [comment]
Oh no! I just noticed that! Sorry!

Okay, I've reverted it now.

**Pull request merged**
